openapi: 3.0.0
info:
  version: 1.0.0
  title: Rierino - Gateway Server - Request APIs
  license:
    name: Commercial

servers:
- url: localhost:1234
  description: Local test server
  
paths:

  /api/request/{channel}/{path}:
  
    get:
      summary: Request with URL parameters for payload
      description: Basic request passed on to the [channel] executor, on [path], where URL parameters are used to populate payload.
      parameters:
        - $ref: '#/components/parameters/channelParam'
        - $ref: '#/components/parameters/pathParam'
      responses:
        '200':
          $ref: '#/components/responses/GenericOK'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/NotImplemented'

    post:
      summary: Request with body for payload
      description: Basic request passed on to the [channel] executor, on [path], where body is used to populate payload.
      parameters:
        - $ref: '#/components/parameters/channelParam'
        - $ref: '#/components/parameters/pathParam'
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          $ref: '#/components/responses/GenericOK'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/NotImplemented'

    put:
      summary: Request with body for payload
      description: Basic request passed on to the [channel] executor, on [path], where body is used to populate payload.
      parameters:
        - $ref: '#/components/parameters/channelParam'
        - $ref: '#/components/parameters/pathParam'
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          $ref: '#/components/responses/GenericOK'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/NotImplemented'
      
    patch:
      summary: Request with body for payload
      description: Basic request passed on to the [channel] executor, on [path], where body is used to populate payload.
      parameters:
        - $ref: '#/components/parameters/channelParam'
        - $ref: '#/components/parameters/pathParam'
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          $ref: '#/components/responses/GenericOK'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/NotImplemented'
      
    delete:
      summary: Request with URL parameters for payload
      description: Basic request passed on to the [channel] executor, on [path], where URL parameters are used to populate payload.
      parameters:
        - $ref: '#/components/parameters/channelParam'
        - $ref: '#/components/parameters/pathParam'
      responses:
        '200':
          $ref: '#/components/responses/GenericOK'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/NotImplemented'
      
  /api/request/full/{channel}/{path}:
  
    get:
      summary: Request with "data" URL parameter as contents
      description: Full body request where [data] URL parameter can contain all details, including origin, auth and payload as a Json string.
      parameters:
        - $ref: '#/components/parameters/channelParam'
        - $ref: '#/components/parameters/pathParam'
        - $ref: '#/components/parameters/dataJsonParam'
      responses:
        '200':
          $ref: '#/components/responses/GenericOK'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/NotImplemented'

    post:
      summary: Request with body for full details
      description: Basic request passed on to the [channel] executor, on [path], where body provides full details, including origin, auth and payload.
      parameters:
        - $ref: '#/components/parameters/channelParam'
        - $ref: '#/components/parameters/pathParam'
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                origin:
                  type: object
                auth:
                  type: object
                payload:
                  type: object
      responses:
        '200':
          $ref: '#/components/responses/GenericOK'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/NotImplemented'
          
  /api/request/full/e/{channel}/{path}:
  
    get:
      summary: Request with "data" URL parameter as base64 contents
      description: Full body request where [data] URL parameter can contain all details, including origin, auth and payload as a base64 encoded Json string.
      parameters:
        - $ref: '#/components/parameters/channelParam'
        - $ref: '#/components/parameters/pathParam'
        - $ref: '#/components/parameters/dataBase64Param'
      responses:
        '200':
          $ref: '#/components/responses/GenericOK'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/NotImplemented'

    post:
      summary: Request with body for base64 encoded details
      description: Basic request passed on to the [channel] executor, on [path], where body is a base64 string encoded Json, which provides full details, including origin, auth and payload.
      parameters:
        - $ref: '#/components/parameters/channelParam'
        - $ref: '#/components/parameters/pathParam'
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: string
              description: Base64 encoding of Json body with origin, auth and payload
      responses:
        '200':
          $ref: '#/components/responses/GenericOK'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'
        '501':
          $ref: '#/components/responses/NotImplemented'
                    
components:

  parameters:
    pathParam:
      name: path
      in: path
      description: "Path for calling specific action / saga on gateway channel"
      required: true
      schema:
        type: string
        example: product
    channelParam:
      name: channel
      in: path
      description: "Gateway channel for execution"
      required: true
      schema:
        type: string
        example: crud
    dataJsonParam:
      name: data
      in: query
      description: "Json string representation of a request"
      required: false
      schema:
        type: string
        example: "{origin:{}, auth:{}, payload:{}}"
    dataBase64Param:
      name: data
      in: query
      description: "Base64 encoded Json string representation of a request"
      required: false
      schema:
        type: string
        example: "e29yaWdpbjp7fSwgYXV0aDp7fSwgcGF5bG9hZDp7fX0="
        
  responses:
    GenericOK:
      description: "OK"
    Unauthorized:
      description: "Authorization information is missing or invalid."
    Forbidden:
      description: "User does not have the required role for access."
    InternalError:
      description: "Server failed to process request due to internal errors."
    NotImplemented:
      description: "Feature is not implemented by the server."
